name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            packages/instant-apps-components/node_modules
            packages/instant-apps-components/.cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --verbose
        working-directory: packages/instant-apps-components

      - name: Install Playwright
        run: npx playwright install
        working-directory: packages/instant-apps-components

      - name: Build project
        run: npm run build
        working-directory: packages/instant-apps-components

      - name: Run tests
        run: npm test
        working-directory: packages/instant-apps-components
